### ISSUE TITLE
Spelling mistake.

### ISSUE THREAD

**Issue by JosephCW** [ihappyhacking/ihappyhacking.github.io#1]
<span class="line">SecIdentityCreateWtihCertificate
"Wtih"

File is located: https://github.com/meilbn/meilbn.github.io/blob/master/2016/11/03/CFHipsterRef-Low-Level-Programming-on-iOS-OSX-Chapter10-Security/index.html

**Comment by meilbn** [comment]
Thanks!
Already modified.
By the way, how did you find it?

**Comment by JosephCW** [comment]
_Poof_ Magic!

Webscrape for a list of repositories that are recently updated, and the code contains 'wtih'.

**Comment by meilbn** [comment]
Wow, this is great!
Thanks, again.

**Comment by JosephCW** [comment]
No problem. :P
